format = """
\\[$shell\\]-\\[$username$hostname\\]-\\[$directory\\]-\\[$time\\]$git_branch$git_status$status
$character"""

add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "λ"
error_symbol = "[λ](bold red)"
vimcmd_symbol = "[λ](dimmed green)"

[shell]
disabled = false
format = "[$indicator]($style)"
style = "blue bold"

[username]
show_always = true
format = "[$user](bold green)"

[hostname]
ssh_only = false
format = "[@$hostname](bold green)[$ssh_symbol](bold red)"
ssh_symbol = "\\(ssh\\)"

[directory]
format = "[$path](bold cyan)"
read_only = "!"
truncation_length = 3
truncate_to_repo = false

[time]
disabled = false
format = "[$time](bold yellow)"
time_format = "%H:%M"

[git_branch]
format = "─\\[[$branch](bold purple)"

[git_status]
format = "([|$all_status$ahead_behind](bold red))\\]"
style = "violet"
conflicted = "!"
untracked = "?"
modified = "*"
staged = "+"
renamed = "»"
deleted = "-"
stashed = "≡"
